### ISSUE TITLE
GRETA/Portfolio plus as an example dynamic competence map

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/dcm#3]
![grafik](https://github.com/WolfgangFahl/dcm/assets/1336221/99405c1e-a62d-4cdd-9fca-dbdd8ad23489)
see also [Muster Komptenzbilanz](https://www.greta-die.de/_Resources/Persistent/1/6/8/3/1683bd4dbd628bef1bf365c4062502023edb8b13/Kompetenzbilanz_Margarethe_Musterfrau_Aufbaustufe.pdf)
### Competence Aspects with Abbreviations:

- BPWK - Berufspraktisches Wissen und Können
- FFW - Fach- und feldspezifisches Wissen
- PWAU - Professionelle Werthaltungen und Überzeugungen
- PSS - Professionelle Selbststeuerung

#### BPWK - Berufspraktisches Wissen und Können:
- Lerninhalte und -ziele
- Methoden, Medien und Lernmaterialien
- Rahmenbedingungen und Lernumgebungen
- Outcomeorientierung
- Teilnehmendenorientierung
- Diagnostik und Lernberatung
- Moderation und Steuerung von Gruppen
- Professionelle Kommunikation
- Kooperation mit den Auftraggebenden/Arbeitgebenden
- Kollegiale Zusammenarbeit/Netzwerken

#### FFW - Fach- und feldspezifisches Wissen:
- Adressatinnen und Adressaten
- Feldspezifisches Wissen
- Curriculare und institutionelle Rahmenbedingungen

#### PSS - Professionelle Selbststeuerung:
- Selbstwirksamkeitsüberzeugungen
- Enthusiasmus
- Eigenes Rollenbewusstsein
- Reflexion des eigenen Lehrhandelns
- Umgang mit Feedback und Kritik
- Engagement und Distanz

#### PWAU - Professionelle Werthaltungen und Überzeugungen:
- Menschenbilder
- Wertvorstellungen
- Berufliche Weiterentwicklung
- Subjektive Annahmen über das Lehren und Lernen

### competence levels
- Basisstufe
- Ausbaustufe
- Nicht erfasst

### RGB Color Codes:

- BPWK: `#B5B0A8`
- FFW: `#D1CFC7`
- PWAU: `#EBE8E5`
- PSS: `#918F82`

**Comment by WolfgangFahl** [comment]
The description shall be encoded in JSON format:
```json
{
  "CompetenceAspects": {
    "BPWK": {
      "FullName": "Berufspraktisches Wissen und Können",
      "ColorCode": "#B5B0A8",
      "Facets": [
        "Lerninhalte und -ziele",
        "Methoden, Medien und Lernmaterialien",
        "Rahmenbedingungen und Lernumgebungen",
        "Outcomeorientierung",
        "Teilnehmendenorientierung",
        "Diagnostik und Lernberatung",
        "Moderation und Steuerung von Gruppen",
        "Professionelle Kommunikation",
        "Kooperation mit den Auftraggebenden/Arbeitgebenden",
        "Kollegiale Zusammenarbeit/Netzwerken"
      ]
    },
    "FFW": {
      "FullName": "Fach- und feldspezifisches Wissen",
      "ColorCode": "#D1CFC7",
      "Facets": [
        "Adressatinnen und Adressaten",
        "Feldspezifisches Wissen",
        "Curriculare und institutionelle Rahmenbedingungen"
      ]
    },
    "PWAU": {
      "FullName": "Professionelle Werthaltungen und Überzeugungen",
      "ColorCode": "#EBE8E5",
      "Facets": [
        "Menschenbilder",
        "Wertvorstellungen",
        "Berufliche Weiterentwicklung",
        "Subjektive Annahmen über das Lehren und Lernen"
      ]
    },
    "PSS": {
      "FullName": "Professionelle Selbststeuerung",
      "ColorCode": "#918F82",
      "Facets": [
        "Selbstwirksamkeitsüberzeugungen",
        "Enthusiasmus",
        "Eigenes Rollenbewusstsein",
        "Reflexion des eigenen Lehrhandelns",
        "Umgang mit Feedback und Kritik",
        "Engagement und Distanz"
      ]
    }
  },
  "CompetenceLevels": [
    "Basisstufe",
    "Ausbaustufe",
    "Nicht erfasst"
  ]
}
```

**Comment by WolfgangFahl** [comment]
see also https://www.greta-die.de/webpages/greta-interaktiv

**Comment by MaxKissgen** [comment]
Possibly related mockups for Greta for switchting between the different competence facettes/points:
Unexpanded, just showing competence facettes:
![Kompetenzbilanz_unexpanded_clicked](https://github.com/WolfgangFahl/dcm/assets/64896977/31d246f3-3fa9-4f2d-b6dd-33ea523d935b)
Expanded via click in the middle:
![Kompetenzbilanz_expanded](https://github.com/WolfgangFahl/dcm/assets/64896977/04d56a1e-d2d5-4680-be1f-09c309211eed)

**Comment by WolfgangFahl** [comment]
see also https://wiki.bitplan.com/index.php/Skills_Wheel

**Comment by WolfgangFahl** [comment]
see #14

**Comment by WolfgangFahl** [comment]
![grafik](https://github.com/WolfgangFahl/dcm/assets/1336221/fc444c24-1b7a-46bd-b821-cc728c5fc701)

**Comment by WolfgangFahl** [comment]
![grafik](https://github.com/WolfgangFahl/dcm/assets/1336221/39ec55fe-3e9d-4561-9de7-02917e327610)

**Comment by WolfgangFahl** [comment]
<img width="647" alt="grafik" src="https://github.com/WolfgangFahl/dcm/assets/1336221/c48b7b0c-bcad-447f-8cb3-6909bbf3c55e">

**Comment by WolfgangFahl** [comment]
Depending on the setting in the YAML file the display is possible with different text angles and ring specs:
<img width="639" alt="grafik" src="https://github.com/WolfgangFahl/dcm/assets/1336221/ae638332-31e7-4174-9e6f-2c0554ff9fdd">

**Comment by WolfgangFahl** [comment]
Popups show the details: 
<img width="547" alt="grafik" src="https://github.com/WolfgangFahl/dcm/assets/1336221/232cef6c-7aae-4a2f-a5d3-45d8382a3966">

**Comment by WolfgangFahl** [comment]
<img width="643" alt="grafik" src="https://github.com/WolfgangFahl/dcm/assets/1336221/d434732a-d206-4d66-93dc-6dd26cdc7d38">
