### ISSUE TITLE
GRETA: multiple levels per facet

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/dcm#50]
For one facet multiple levels are possible.

All combination are possible.

Learning Records will have the assessments ...

Statements ...

**Comment by derFint** [comment]
Is it possible to get an example of how to adapt the data schema for microcredentials (#53 ) in order to send a result that enables the dcm to show multiple levels?

**Comment by WolfgangFahl** [comment]
will be traced at https://git.dbis.rwth-aachen.de/ACIS/trainspot/dcm/-/issues/50
